Add files via upload

diff --git a/roles/create_standby/templates/restore_standby_db.sh.j2 b/roles/create_standby/templates/restore_standby_db.sh.j2
--- a/roles/create_standby/templates/restore_standby_db.sh.j2
+++ b/roles/create_standby/templates/restore_standby_db.sh.j2
@@ -102,18 +102,8 @@ if [[ "$WITH_BACKUP" == "true" ]]; then
  }
  EXIT;
 EOF
-
-    # Capture RMAN exit status
-    rman_exit_code=$?
-
-    # Check if the RMAN command was successful and ensure there are no RMAN- errors in the log
-    if [ $rman_exit_code -eq 0 ] && ! grep -q "RMAN-" "$MASTER_LOG"; then
-        echo "RMAN restore for Dataguard setup completed successfully." | tee -a $MASTER_LOG
-        touch "{{ done_dir }}/standby_restore.success"
-    else
-        echo "RMAN restore for Dataguard setup failed! Check logs for details: $MASTER_LOG" | tee -a "$FAILURE_LOG"
-        exit 1
-    fi
+# Capture RMAN exit status
+rman_exit_code=$?
 
 elif [[ "$WITH_BACKUP" == "false" ]]; then
 
@@ -159,24 +149,22 @@ elif [[ "$WITH_BACKUP" == "false" ]]; then
  }
 EXIT;
 EOF
-        # Capture RMAN exit status
-        rman_exit_code=$?
-        echo "RMAN exit code: $rman_exit_code" | tee -a "$MASTER_LOG"
-        grep "RMAN-" "$MASTER_LOG" >> "$FAILURE_LOG"
-        # Check if the RMAN command log contains any RMAN- errors
-        if grep -q "RMAN-" "$MASTER_LOG"; then
-            echo "Duplicate Target Dataguard setup failed! Check logs for details: $MASTER_LOG" | tee -a "$FAILURE_LOG"
-            exit 1
-        else
-            echo "Duplicate Target Dataguard setup completed successfully." | tee -a "$MASTER_LOG"
-            touch "{{ done_dir }}/standby_restore.success"
-        fi
+# Capture RMAN exit status
+rman_exit_code=$?
 
 else
     echo "ERROR: Invalid value for 'with_backup'. Please provide 'true' or 'false'." | tee -a "$FAILURE_LOG"
     exit 1
 
+fi
 
+# Check if the RMAN command was successful and ensure there are no RMAN- errors in the log
+if [ $rman_exit_code -eq 0 ]; then
+    echo "Dataguard setup completed successfully." | tee -a $MASTER_LOG
+    touch "{{ done_dir }}/standby_restore.success"
+else
+    echo "Dataguard setup failed! Check logs for details: $MASTER_LOG" | tee -a "$FAILURE_LOG"
+    exit 1
 fi
 
 #Check for failures and exit accordingly
