Update restore_standby_db.sh.j2

diff --git a/roles/create_standby/templates/restore_standby_db.sh.j2 b/roles/create_standby/templates/restore_standby_db.sh.j2
--- a/roles/create_standby/templates/restore_standby_db.sh.j2
+++ b/roles/create_standby/templates/restore_standby_db.sh.j2
@@ -17,10 +17,6 @@ standby_diskgroup={{ databases[database_name].file_dest }}
 # Check if the standby database is already running by checking PMON process
 if ps -ef | grep "pmon" | grep -q "$ORACLE_SID"; then
     echo "Standby database is already running." | tee -a "$MASTER_LOG"
-    su - {{ db_oracle_user }} -c "sqlplus -s / as sysdba" <<SQL | tee -a "$MASTER_LOG"
-    shut immediate;
-    startup nomount;
-SQL
 else
     echo "Starting standby database..." | tee -a "$MASTER_LOG"
     su - {{ db_oracle_user }} -c "sqlplus -s / as sysdba" <<SQL | tee -a "$MASTER_LOG"
@@ -30,6 +26,7 @@ fi
 
 # Convert 'with_backup' variable to lowercase for consistency
 WITH_BACKUP="$(echo {{ with_backup | default('no') }} | tr '[:upper:]' '[:lower:]')"
+# RMAN restore Backup-based
 if [[ "$WITH_BACKUP" == "true" ]]; then
 
  {% set backup_format = backup_location ~ '/%U' %}
@@ -52,34 +49,50 @@ if [[ "$WITH_BACKUP" == "true" ]]; then
 standby_cpu_core=$(lsdev -Cc processor | wc -l)
 primary_cpu_core={{ primary_cpu_core }}
 
- su - {{ db_oracle_user }} -c "rman target /" <<EOF | tee "$MASTER_LOG"
- RUN {
-    $(for (( i=1; i<=${standby_cpu_core}; i++ )); do
-        echo "ALLOCATE CHANNEL ch$i DEVICE TYPE DISK ;"
-    done)
+# Generate the RMAN script dynamically
+RMAN_SCRIPT="/tmp/ansible/scripts/rman_restore.rcv"
 
-     set dbid {{ dbid }};
-     
-     # Identify the latest control file backup dynamically
-     restore standby controlfile from '$LATEST_CONTROLFILE';
-     sql "alter database mount standby database";
-     
-     # Catalog the backup pieces if needed
-     catalog start with '{{ backup_location }}/' noprompt;
-     
-     restore database;
-     switch datafile all;
-     recover database;
- 
-     $(for (( i=1; i<=total_cores; i++ )); do
-     echo "    RELEASE CHANNEL ch$i;"
- done)
- }
- EXIT;
-EOF
+{
+    echo "RUN {"
+
+    # Allocate channels dynamically
+    i=1
+    while [ "$i" -le "$standby_cpu_core" ]; do
+        echo "    ALLOCATE CHANNEL ch$i DEVICE TYPE DISK ;"
+        i=`expr $i + 1`
+    done
+
+    echo "    set dbid 1719927505;"
+    echo ""
+    echo "    # Identify the latest control file backup dynamically"
+    echo "    restore standby controlfile from '$LATEST_CONTROLFILE';"
+    echo "    sql \"alter database mount standby database\";"
+    echo ""
+    echo "    # Catalog the backup pieces if needed"
+    echo "    catalog start with '/u01/backup/' noprompt;"
+    echo ""
+    echo "    restore database;"
+    echo "    switch datafile all;"
+    echo "    recover database;"
+    echo ""
+
+    # Release channels dynamically
+    i=1
+    while [ "$i" -le "$standby_cpu_core" ]; do
+        echo "    RELEASE CHANNEL ch$i;"
+        i=`expr $i + 1`
+    done
+
+    echo "}"
+    echo "EXIT;"
+} > "$RMAN_SCRIPT"
+
+su - {{ db_oracle_user }} -c "rman target / log=$MASTER_LOG @/tmp/ansible/scripts/rman_restore.rcv"
+
 # Capture RMAN exit status
 rman_exit_code=$?
 
+# Rman Duplicate from active database
 elif [[ "$WITH_BACKUP" == "false" ]]; then
 
  # Define values dynamically
@@ -95,35 +108,41 @@ elif [[ "$WITH_BACKUP" == "false" ]]; then
  db_recovery_file_dest="{{ databases[database_name].db_recovery_file_dest }}"
  db_recovery_file_dest_size="{{ databases[database_name].db_recovery_file_dest_size }}"
  
- su - {{ db_oracle_user }} -c "rman target {{ sys_user }}/{{ default_dbpass }}@{{ databases.primary.db_sid }} auxiliary {{ sys_user }}/{{ default_dbpass }}@${standby_unique_name}" <<EOF | tee "$MASTER_LOG"
- RUN {
-      $(for (( i=1; i<=${primary_cpu_core}; i++ )); do
-        echo "ALLOCATE CHANNEL prmy$i DEVICE TYPE DISK ;"
-    done)
-      ALLOCATE auxiliary CHANNEL stby TYPE DISK;
+ {
+    echo "RUN {"
+
+    # Allocate channels dynamically
+    i=1
+    while [ "$i" -le "$primary_cpu_core" ]; do
+        echo "    ALLOCATE CHANNEL prmy$i DEVICE TYPE DISK ;"
+        i=`expr $i + 1`
+    done
       
-      duplicate target database for standby from active database NOFILENAMECHECK
-      spfile
-        parameter_value_convert '${primary_unique_name}','${standby_unique_name}'
-        set db_name='${primary_unique_name}'
-        set db_create_file_dest='${db_create_file_dest}'
-        set db_unique_name='${standby_unique_name}'
-        set db_file_name_convert='${db_file_name_convert}'
-        set log_file_name_convert='${log_file_name_convert}'
-        set control_files='${db_create_file_dest}/${standby_unique_name}/CONTROLFILE/${standby_unique_name}_control01.ctl'
-        set log_archive_max_processes='5'
-        set fal_client='${standby_unique_name}'
-        set fal_server='${primary_unique_name}'
-        set standby_file_management='MANUAL'
-        set log_archive_config='dg_config=(${primary_unique_name},${standby_unique_name})'
-        set log_archive_dest_2='service=${primary_unique_name} ASYNC valid_for=(ONLINE_LOGFILE,PRIMARY_ROLE) db_unique_name=${primary_unique_name}'
-        set db_create_online_log_dest_1='${db_create_online_log_dest_1}'
-        set db_recovery_file_dest='${db_recovery_file_dest}'
-        set db_recovery_file_dest_size='${db_recovery_file_dest_size}'
- ;
- }
-EXIT;
-EOF
+      echo " duplicate target database for standby from active database NOFILENAMECHECK
+      echo " spfile
+      echo "   parameter_value_convert '${primary_unique_name}','${standby_unique_name}'
+      echo "   set db_name='${primary_unique_name}'
+      echo "   set db_create_file_dest='${db_create_file_dest}'
+      echo "   set db_unique_name='${standby_unique_name}'
+      echo "   set db_file_name_convert='${db_file_name_convert}'
+      echo "   set log_file_name_convert='${log_file_name_convert}'
+      echo "   set control_files='${db_create_file_dest}/${standby_unique_name}/CONTROLFILE/${standby_unique_name}_control01.ctl'
+      echo "   set log_archive_max_processes='5'
+      echo "   set fal_client='${standby_unique_name}'
+      echo "   set fal_server='${primary_unique_name}'
+      echo "   set standby_file_management='MANUAL'
+      echo "   set log_archive_config='dg_config=(${primary_unique_name},${standby_unique_name})'
+      echo "   set log_archive_dest_2='service=${primary_unique_name} ASYNC valid_for=(ONLINE_LOGFILE,PRIMARY_ROLE) db_unique_name=${primary_unique_name}'
+      echo "   set db_create_online_log_dest_1='${db_create_online_log_dest_1}'
+      echo "   set db_recovery_file_dest='${db_recovery_file_dest}'
+      echo "   set db_recovery_file_dest_size='${db_recovery_file_dest_size}'
+      echo " ;
+      echo "}"
+      echo "EXIT;"
+} > "$RMAN_SCRIPT"
+
+su - {{ db_oracle_user }} -c "rman target {{ sys_user }}/{{ default_dbpass }}@{{ databases.primary.db_sid }} auxiliary {{ sys_user }}/{{ default_dbpass }}@${standby_unique_name} log=$MASTER_LOG @/tmp/ansible/scripts/rman_duplicate.rcv"
+
 # Capture RMAN exit status
 rman_exit_code=$?
 
@@ -133,13 +152,16 @@ else
 
 fi
 
-# Check if the RMAN command was successful and ensure there are no RMAN- errors in the log
-if [ $rman_exit_code -eq 0 ] && ! grep -q "ORA-" "$MASTER_LOG" && ! grep -q "ERROR" "$MASTER_LOG"; then
-    echo "Dataguard setup completed successfully." | tee -a $MASTER_LOG
-    touch "{{ done_dir }}/standby_restore.success"
+if [[ $rman_exit_code -eq 0 ]]; then
+    echo "RMAN completed successfully." | tee -a "$MASTER_LOG"
+elif [[ $rman_exit_code -eq 1 ]]; then
+    echo "RMAN completed with warnings. Check logs for details." | tee -a "$MASTER_LOG"
+elif [[ $rman_exit_code -eq 2 ]]; then
+    echo "RMAN failed due to errors. Review the log: $MASTER_LOG" | tee -a "$FAILURE_LOG"
+    exit 2
 else
-    echo "Dataguard setup failed! Check logs for details: $MASTER_LOG" | tee -a "$FAILURE_LOG"
-    exit 1
+    echo "RMAN encountered a fatal error!" | tee -a "$FAILURE_LOG"
+    exit 3
 fi
 
 #Check for failures and exit accordingly
