Add files via upload

diff --git a/roles/create_standby/templates/restore_standby_db.sh.j2 b/roles/create_standby/templates/restore_standby_db.sh.j2
--- a/roles/create_standby/templates/restore_standby_db.sh.j2
+++ b/roles/create_standby/templates/restore_standby_db.sh.j2
@@ -3,13 +3,17 @@
 export ORACLE_SID=$(ps -ef | grep pmon | grep ASM | awk '{match($NF, /\+ASM[0-9]*/); print substr($NF, RSTART, RLENGTH)}')
 export ORACLE_HOME=$(awk -F: -v sid="$ORACLE_SID" '$1 == sid {print $2}' /etc/oratab)
 export PATH=$PATH:$ORACLE_HOME/bin
-
 MASTER_LOG="{{ done_dir }}/standby_rman_restore.log"
 FAILURE_LOG="{{ done_dir }}/standby_rman_restore_fail.log"
 
 # Ensure log files are empty before running
 > "$MASTER_LOG"
 > "$FAILURE_LOG"
+
+if [[ -z "$ORACLE_HOME" ]]; then
+  echo "ERROR: ORACLE_HOME is not set for ASM. Check /etc/oratab and update accordingly" | tee -a "$FAILURE_LOG"
+  exit 1
+fi
 
 # Fetch the disk group name from standby ASM
 su - {{ grid_user }} -c "sqlplus -s / as sysdba" <<SQL | tee "$MASTER_LOG"
@@ -28,13 +32,13 @@ SQL
 DISKGROUP=$(grep "DISKGROUP:" "$MASTER_LOG" | awk -F ':' '{print $2}')
 
 # Check if disk group was retrieved
-if [[ -z "$DISKGROUP" ]]; then
+if [[ -z "$DISKGROUP" || "$DISKGROUP" == "DISKGROUP:" ]]; then
   echo "ERROR:Failed to fetch disk group from standby ASM, verify manually and retry" | tee -a "$FAILURE_LOG"
   exit 1
 fi
 
+# Define values dynamically
 diskgroup="+${DISKGROUP}"
-
 export ORACLE_SID={{ databases[database_name].oracle_db_sid }}
 export ORACLE_HOME={{ databases[database_name].oracle_db_home }}
 export PATH={{ databases[database_name].oracle_db_home }}/bin:$PATH
@@ -46,62 +50,113 @@ startup nomount;
 SQL
 
 # Run rman restore
+if [[ "$(echo {{ with_backup | default('no') }} | tr '[:upper:]' '[:lower:]')" == "yes" ]]; then 
 
-{% set backup_format = backup_location ~ '/%U' %}
-{% set ctrl_backup_format = backup_location ~ '/controlfile_%d_%T_%s_%p.bkp' %}
-{% set controlfile_tag = "CONTROLFILE_BACKUP" %}
-{% set fullbackup_tag = "FULL_ARC_BACKUP" %}
+ {% set backup_format = backup_location ~ '/%U' %}
+ {% set ctrl_backup_format = backup_location ~ '/controlfile_%d_%T_%s_%p.bkp' %}
+ {% set controlfile_tag = "CONTROLFILE_BACKUP" %}
+ {% set fullbackup_tag = "FULL_ARC_BACKUP" %}
+ 
+ # Get the latest control file backup
+ LATEST_CONTROLFILE=$(ls -t {{ backup_location }}/controlfile_*.bkp  | head -1)
+ 
+ # Check if a control file backup exists
+   if [[ -z "$LATEST_CONTROLFILE" ]]; then
+       echo "ERROR: No control file backup found!"
+       exit 1
+   fi
+ 
+ echo "Using latest control file backup: $LATEST_CONTROLFILE"
+ 
+ su - {{ db_oracle_user }} -c "rman target /" <<EOF | tee "$MASTER_LOG"
+ RUN {
+     ALLOCATE CHANNEL ch1 DEVICE TYPE DISK;
+     ALLOCATE CHANNEL ch2 DEVICE TYPE DISK;
+     ALLOCATE CHANNEL ch3 DEVICE TYPE DISK;
+     ALLOCATE CHANNEL ch4 DEVICE TYPE DISK;
+     
+     set dbid {{ dbid }};
+     
+     # Identify the latest control file backup dynamically
+     restore standby controlfile from '$LATEST_CONTROLFILE';
+     sql "alter database mount standby database";
+     
+     # Catalog the backup pieces if needed
+     catalog start with '{{ backup_location }}/' noprompt;
+     
+     # Restore database
+     set newname for database to '${diskgroup}';
+     restore database;
+     switch datafile all;
+     recover database;
+ 
+     RELEASE CHANNEL ch1;
+     RELEASE CHANNEL ch2;
+     RELEASE CHANNEL ch3;
+     RELEASE CHANNEL ch4;
+ }
+ EXIT;
+EOF
 
-# Get the latest control file backup
-LATEST_CONTROLFILE=$(ls -t {{ backup_location }}/controlfile_*.bkp  | head -1)
+elif [[ "$(echo {{ with_backup | default('no') }} | tr '[:upper:]' '[:lower:]')" == "no" ]]; then
 
-# Check if a control file backup exists
-if [[ -z "$LATEST_CONTROLFILE" ]]; then
-    echo "ERROR: No control file backup found!"
-    exit 1
-fi
-
-echo "Using latest control file backup: $LATEST_CONTROLFILE"
-
-su - {{ db_oracle_user }} -c "rman target /" <<EOF | tee "$MASTER_LOG"
-RUN {
-    ALLOCATE CHANNEL ch1 DEVICE TYPE DISK;
-    ALLOCATE CHANNEL ch2 DEVICE TYPE DISK;
-    ALLOCATE CHANNEL ch3 DEVICE TYPE DISK;
-    ALLOCATE CHANNEL ch4 DEVICE TYPE DISK;
-    
-    set dbid {{ dbid }};
-    
-    # Identify the latest control file backup dynamically
-    restore standby controlfile from '$LATEST_CONTROLFILE';
-    sql "alter database mount standby database";
-    
-    # Catalog the backup pieces if needed
-    catalog start with '{{ backup_location }}/' noprompt;
-    
-    # Restore database
-    set newname for database to '${diskgroup}';
-    restore database;
-    switch datafile all;
-    recover database;
-
-    RELEASE CHANNEL ch1;
-    RELEASE CHANNEL ch2;
-    RELEASE CHANNEL ch3;
-    RELEASE CHANNEL ch4;
-}
+ # Define values dynamically
+ ORACLE_HOME={{ databases.standby.oracle_db_home }}
+ ORACLE_SID={{ databases.standby.oracle_db_sid }}
+ standby_diskgroup="+${DISKGROUP}"
+ primary_diskgroup={{ primary_diskgroup }}
+ PRIMARY_UNIQUE_NAME="{{ databases.primary.oracle_db_unique_name }}"
+ PRIMARY_DB_NAME="{{ databases.primary.oracle_db_name }}"
+ STANDBY_UNIQUE_NAME="{{ databases.standby.oracle_db_unique_name }}"
+ log_file_name_convert="'${primary_diskgroup}/${PRIMARY_UNIQUE_NAME}','${standby_diskgroup}/${STANDBY_UNIQUE_NAME}'"
+ db_file_name_convert="'${primary_diskgroup}/${PRIMARY_UNIQUE_NAME}','${standby_diskgroup}/${STANDBY_UNIQUE_NAME}'"
+ db_recovery_file_dest="{{ databases.standby.db_recovery_file_dest }}"
+ db_recovery_file_dest_size="{{ databases.standby.db_recovery_file_dest_size }}"
+ 
+ su - {{ db_oracle_user }} -c "rman target sys/{{ default_dbpass }}@{{ databases.primary.oracle_db_sid }} auxiliary sys/{{ default_dbpass }}@${ORACLE_SID}" <<EOF | tee "$MASTER_LOG"
+ RUN {
+      ALLOCATE CHANNEL prmy1 TYPE DISK;
+      ALLOCATE CHANNEL prmy2 TYPE DISK;
+      ALLOCATE CHANNEL prmy3 TYPE DISK;
+      ALLOCATE CHANNEL prmy4 TYPE DISK;
+      ALLOCATE auxiliary CHANNEL stby TYPE DISK;
+      
+      duplicate target database for standby from active database NOFILENAMECHECK
+      spfile
+        parameter_value_convert '${PRIMARY_UNIQUE_NAME}','${STANDBY_UNIQUE_NAME}'
+        set db_name='${PRIMARY_UNIQUE_NAME}'
+        set db_create_file_dest='${standby_diskgroup}'
+        set db_unique_name='${STANDBY_UNIQUE_NAME}'
+        set db_file_name_convert='${primary_diskgroup}/${PRIMARY_UNIQUE_NAME}','${standby_diskgroup}/${STANDBY_UNIQUE_NAME}'
+        set log_file_name_convert='${primary_diskgroup}/${PRIMARY_UNIQUE_NAME}','${standby_diskgroup}/${STANDBY_UNIQUE_NAME}'
+        set control_files='${standby_diskgroup}/${STANDBY_UNIQUE_NAME}/CONTROLFILE/${STANDBY_UNIQUE_NAME}_control01.ctl'
+        set log_archive_max_processes='5'
+        set fal_client='${STANDBY_UNIQUE_NAME}'
+        set fal_server='${PRIMARY_UNIQUE_NAME}'
+        set standby_file_management='MANUAL'
+        set log_archive_config='dg_config=(${PRIMARY_UNIQUE_NAME},${STANDBY_UNIQUE_NAME})'
+        set log_archive_dest_2='service=${PRIMARY_UNIQUE_NAME} ASYNC valid_for=(ONLINE_LOGFILE,PRIMARY_ROLE) db_unique_name=${PRIMARY_UNIQUE_NAME}'
+        set db_recovery_file_dest='${db_recovery_file_dest}''
+        set db_recovery_file_dest_size='${db_recovery_file_dest_size}'
+ ;
+ }
 EXIT;
 EOF
+
+else
+    echo "ERROR: Invalid value for 'with_backup'. Please provide 'yes' or 'no'." | tee -a "$FAILURE_LOG"
+    exit 1
+fi
 
 # Capture RMAN exit status
 rman_exit_code=$?
 
 # Check if the RMAN command was successful
-if [ $rman_exit_code -eq 0 ] && grep -qi "Finished restore at" "$MASTER_LOG" && grep -qi "Media Recovery complete" "$MASTER_LOG"; then
-    echo "RMAN restore completed successfully." | tee -a $MASTER_LOG
+if [ $rman_exit_code -eq 0 ] ; then
+    echo "Dataguard setup completed successfully." | tee -a $MASTER_LOG
     touch "{{ done_dir }}/standby_restore.success"
 else
-    echo "RMAN restore failed! Check logs for details: $MASTER_LOG" | tee -a "$FAILURE_LOG"
+    echo "Dataguard setup failed! Check logs for details: $MASTER_LOG" | tee -a "$FAILURE_LOG"
     exit 1
 fi
 
@@ -112,6 +167,6 @@ if [[ -s "$FAILURE_LOG" ]]; then
     exit 1
 fi
 
-echo "RMAN restore performed for standby database successfully!"
+echo "Dataguard setup completed successfully!"
 rm -f "$FAILURE_LOG"
 exit 0
diff --git a/roles/preconfig_standby/templates/standby_preconfig.sh.j2 b/roles/preconfig_standby/templates/standby_preconfig.sh.j2
--- a/roles/preconfig_standby/templates/standby_preconfig.sh.j2
+++ b/roles/preconfig_standby/templates/standby_preconfig.sh.j2
@@ -3,17 +3,26 @@
 export ORACLE_SID=$(ps -ef | grep pmon | grep ASM | awk '{match($NF, /\+ASM[0-9]*/); print substr($NF, RSTART, RLENGTH)}')
 export ORACLE_HOME=$(awk -F: -v sid="$ORACLE_SID" '$1 == sid {print $2}' /etc/oratab)
 export PATH=$PATH:$ORACLE_HOME/bin
-PORT=$(su - grid -c "$ORACLE_HOME/bin/lsnrctl status | grep PORT | awk -F'PORT=' '{print \$2}' | awk -F')' '{print \$1}' | sort -u | head -1")
-
-
-
-
 MASTER_LOG="{{ done_dir }}/standby_preconfig.log"
 FAILURE_LOG="{{ done_dir }}/standby_preconfig_failure.log"
 
 # Ensure log files are empty before running
 > "$MASTER_LOG"
 > "$FAILURE_LOG"
+
+if [[ -z "$ORACLE_HOME" ]]; then
+  echo "ERROR: ORACLE_HOME is not set for ASM. Check /etc/oratab and update accordingly" | tee -a "$FAILURE_LOG"
+  exit 1
+fi
+
+if su - grid -c "$ORACLE_HOME/bin/lsnrctl status" 2>&1 | grep -q "TNS-12541"; then
+  echo "ERROR: Listener is down. Start the listener and retry." | tee -a "$FAILURE_LOG"
+  exit 1
+fi
+
+# Fetch port and listener.ora file location
+PORT=$(su - grid -c "$ORACLE_HOME/bin/lsnrctl status | grep PORT | awk -F'PORT=' '{print \$2}' | awk -F')' '{print \$1}' | sort -u | head -1")
+listener_file=$(su - grid -c "$ORACLE_HOME/bin/lsnrctl status | grep \"Listener Parameter File\" | awk '{print \$NF}'")
 
 # Fetch the disk group name from standby ASM
 su - {{ grid_user }} -c "sqlplus -s / as sysdba" <<SQL | tee "$MASTER_LOG"
@@ -32,22 +41,20 @@ SQL
 DISKGROUP=$(grep "DISKGROUP:" "$MASTER_LOG" | awk -F ':' '{print $2}')
 
 # Check if disk group was retrieved
-if [[ -z "$DISKGROUP" ]]; then
+if [[ -z "$DISKGROUP" || "$DISKGROUP" == "DISKGROUP:" ]]; then
   echo "ERROR:Failed to fetch disk group from standby ASM, verify manually and retry" | tee -a "$FAILURE_LOG"
   exit 1
 fi
 
-# Take a backup before modifying
-cp {{ databases.standby.oracle_db_home }}/dbs/standby.pfile {{ databases.standby.oracle_db_home }}/dbs/init{{ databases.standby.oracle_db_sid }}.ora
-PFILE={{ databases.standby.oracle_db_home }}/dbs/init{{ databases.standby.oracle_db_sid }}.ora
-TMP_FILE="${PFILE}.tmp"
-
 # Define values dynamically
-oracle_db_unique_name="{{ databases.standby.oracle_db_unique_name }}"
+ORACLE_HOME={{ databases.standby.oracle_db_home }}
+ORACLE_SID={{ databases.standby.oracle_db_sid }}
+PFILE=${ORACLE_HOME}/dbs/init${ORACLE_SID}.ora
 oracle_db_base="{{ databases.standby.oracle_db_base }}"
 standby_diskgroup="+${DISKGROUP}"
 primary_diskgroup={{ primary_diskgroup }}
 PRIMARY_UNIQUE_NAME="{{ databases.primary.oracle_db_unique_name }}"
+PRIMARY_DB_NAME="{{ databases.primary.oracle_db_name }}"
 STANDBY_UNIQUE_NAME="{{ databases.standby.oracle_db_unique_name }}"
 db_recovery_file_dest="{{ databases.standby.db_recovery_file_dest }}"
 db_recovery_file_dest_size="{{ databases.standby.db_recovery_file_dest_size }}"
@@ -57,15 +64,23 @@ log_archive_config="'DG_CONFIG=(${STANDBY_UNIQUE_NAME},${PRIMARY_UNIQUE_NAME})'"
 control_files="'${standby_diskgroup}'"
 log_file_name_convert="'${primary_diskgroup}/${PRIMARY_UNIQUE_NAME}','${standby_diskgroup}/${STANDBY_UNIQUE_NAME}'"
 db_file_name_convert="'${primary_diskgroup}/${PRIMARY_UNIQUE_NAME}','${standby_diskgroup}/${STANDBY_UNIQUE_NAME}'"
-audit_file_dest="'${oracle_db_base}/admin/${oracle_db_unique_name}/adump'"
+audit_file_dest="'${oracle_db_base}/admin/${STANDBY_UNIQUE_NAME}/adump'"
 local_listener="'(ADDRESS=(PROTOCOL=TCP)(HOST={{ standby_host }})(PORT=${PORT}))'"
 
-# Remove all matching parameters in one go and create a temp file
-awk 'tolower($0) !~ /(db_unique_name|audit_file_dest|log_archive_dest_1|control_files|log_file_name_convert|db_file_name_convert|db_create_file_dest)/' "$PFILE" > "$TMP_FILE"
 
-# Append updated parameters at the end
-cat <<EOF >> "$TMP_FILE"
-*.db_unique_name = ${oracle_db_unique_name}
+# Handling backup condition
+if [[ "$(echo {{ with_backup | default('no') }} | tr '[:upper:]' '[:lower:]')" == "yes" ]]; then
+
+  # Take a backup before modifying
+  cp ${ORACLE_HOME}/dbs/standby.pfile "$PFILE"
+  TMP_FILE="${PFILE}.tmp"
+
+  # Remove all matching parameters in one go and create a temp file
+  awk 'tolower($0) !~ /(db_unique_name|audit_file_dest|log_archive_dest_1|control_files|log_file_name_convert|db_file_name_convert|db_create_file_dest)/' "$PFILE" > "$TMP_FILE"
+
+  # Append updated parameters at the end
+  cat <<EOF >> "$TMP_FILE"
+*.db_unique_name = ${STANDBY_UNIQUE_NAME}
 *.audit_file_dest = ${audit_file_dest}
 *.log_archive_dest_1 = ${log_archive_dest_1}
 *.control_files = ${control_files}
@@ -78,14 +93,42 @@ cat <<EOF >> "$TMP_FILE"
 *.LOCAL_LISTENER= ${local_listener}
 EOF
 
-# Replace the original file
-mv "$TMP_FILE" "$PFILE"
-chown {{ db_oracle_user }}:{{ db_oinstall_group }} {{ databases.standby.oracle_db_home }}/dbs/init{{ databases.standby.oracle_db_sid }}.ora
-chmod 755 {{ databases.standby.oracle_db_home }}/dbs/init{{ databases.standby.oracle_db_sid }}.ora
+  # Replace the original file
+  mv "$TMP_FILE" "$PFILE"
+  chown {{ db_oracle_user }}:{{ db_oinstall_group }} "$PFILE"
+  chmod 755 "$PFILE"
 
-# Verify changes
-echo "Updated standby.pfile:"
-cat {{ databases.standby.oracle_db_home }}/dbs/init{{ databases.standby.oracle_db_sid }}.ora
+  # Verify changes
+  echo "Updated standby.pfile:"
+  cat "$PFILE"
+
+elif [[ "$(echo {{ with_backup | default('no') }} | tr '[:upper:]' '[:lower:]')" == "no" ]]; then
+
+# Insert a static entry for standby in the listener.ora file if not updated before
+    if ! grep -q "${STANDBY_UNIQUE_NAME}" "$listener_file"; then
+        cp "$listener_file" "${listener_file}.bak"
+        echo "Updating listener.ora..."
+        cat <<EOF >> "$listener_file"
+SID_LIST_LISTENER =
+(SID_LIST =
+(SID_DESC =
+ (GLOBAL_DBNAME = ${STANDBY_UNIQUE_NAME})
+ (ORACLE_HOME = ${ORACLE_HOME})
+ (SID_NAME = ${ORACLE_SID})
+)
+)
+EOF
+    fi
+  
+    # Create an initialization parameter with only DB_NAME
+  echo "DB_NAME=${PRIMARY_DB_NAME}" > "$PFILE"
+  chown {{ db_oracle_user }}:{{ db_oinstall_group }} "$PFILE"
+  chmod 755 "$PFILE"
+
+else
+    echo "ERROR: Invalid value for 'with_backup'. Please provide 'yes' or 'no'." | tee -a "$FAILURE_LOG"
+    exit 1
+fi
 
 #  Check for failures and exit accordingly
 if [[ -s "$FAILURE_LOG" ]]; then
