Add files via upload

diff --git a/roles/create_standby/templates/restore_standby_db.sh.j2 b/roles/create_standby/templates/restore_standby_db.sh.j2
--- a/roles/create_standby/templates/restore_standby_db.sh.j2
+++ b/roles/create_standby/templates/restore_standby_db.sh.j2
@@ -103,6 +103,22 @@ if [[ "$WITH_BACKUP" == "true" ]]; then
  EXIT;
 EOF
 
+    # Capture RMAN exit status
+    rman_exit_code=$?
+
+    # Check if the RMAN command was successful and ensure there are no RMAN- errors in the log
+    if [ $rman_exit_code -eq 0 ] && ! grep -q "RMAN-" "$MASTER_LOG"; then
+        echo "RMAN restore for Dataguard setup completed successfully." | tee -a $MASTER_LOG
+        touch "{{ done_dir }}/standby_restore.success"
+    else
+        echo "RMAN restore for Dataguard setup failed! Check logs for details: $MASTER_LOG" | tee -a "$FAILURE_LOG"
+        exit 1
+    fi
+
+    else
+        echo "ERROR: Invalid value for 'with_backup'. Please provide 'true' or 'false'." | tee -a "$FAILURE_LOG"
+        exit 1
+
 elif [[ "$WITH_BACKUP" == "false" ]]; then
 
  # Define values dynamically
@@ -148,21 +164,18 @@ elif [[ "$WITH_BACKUP" == "false" ]]; then
 EXIT;
 EOF
 
-else
-    echo "ERROR: Invalid value for 'with_backup'. Please provide 'true' or 'false'." | tee -a "$FAILURE_LOG"
-    exit 1
-fi
+        # Check if the RMAN command was successful and ensure there are no RMAN- errors in the log
+        if ! grep -q "RMAN-" "$MASTER_LOG"; then
+            echo "Duplicate Target Dataguard setup completed successfully." | tee -a $MASTER_LOG
+            touch "{{ done_dir }}/standby_restore.success"
+        else
+            echo "Duplicate Target Dataguard setup failed! Check logs for details: $MASTER_LOG" | tee -a "$FAILURE_LOG"
+            exit 1
+        fi
 
-# Capture RMAN exit status
-rman_exit_code=$?
-
-# Check if the RMAN command was successful and ensure there are no RMAN- errors in the log
-if [ $rman_exit_code -eq 0 ] && ! grep -q "RMAN-" "$MASTER_LOG"; then
-    echo "Dataguard setup completed successfully." | tee -a $MASTER_LOG
-    touch "{{ done_dir }}/standby_restore.success"
-else
-    echo "Dataguard setup failed! Check logs for details: $MASTER_LOG" | tee -a "$FAILURE_LOG"
-    exit 1
+        else
+            echo "ERROR: Invalid value for 'with_backup'. Please provide 'true' or 'false'." | tee -a "$FAILURE_LOG"
+            exit 1
 fi
 
 #Check for failures and exit accordingly
