Update sync_gap.sh.j2

diff --git a/roles/sync_gap/templates/sync_gap.sh.j2 b/roles/sync_gap/templates/sync_gap.sh.j2
--- a/roles/sync_gap/templates/sync_gap.sh.j2
+++ b/roles/sync_gap/templates/sync_gap.sh.j2
@@ -79,10 +79,30 @@ SQL
             SET TRIMSPOOL ON
 
             ALTER DATABASE RECOVER MANAGED STANDBY DATABASE DISCONNECT FROM SESSION;
+            SELECT 'MRP_RUNNING:' || COUNT(*) FROM V\$MANAGED_STANDBY WHERE PROCESS='MRP0';
+SQL
+            # Recheck if MRP0 started
+            MRP_RUNNING=$(grep "MRP_RUNNING:" "$MASTER_LOG" | awk -F '[:,]' '{print $2}')
+                if [[ "$MRP_RUNNING" -eq 0 ]]; then
+                    echo "ERROR: MRP0 process failed to start!" | tee -a "$FAILURE_LOG"
+                    exit 1
+                fi
+            # Wait for standby to catch up
+            echo "Waiting for 180 seconds to allow standby to sync..." | tee -a "$MASTER_LOG"
+            sleep 180
+            # Capture latest sequence number on standby
+            su - {{ db_oracle_user }} -c "sqlplus -s / as sysdba" <<SQL | tee -a "$MASTER_LOG"
+            SET HEADING OFF
+            SET FEEDBACK OFF
+            SET PAGESIZE 0
+            SET LINESIZE 1000
+            SET TRIMOUT ON
+            SET TRIMSPOOL ON
+
             SELECT 'STANDBY_SEQ:' || SEQUENCE# FROM V\$MANAGED_STANDBY WHERE PROCESS='MRP0';
 SQL
         fi
-
+        
         # Get sequence# if MRP process is running 
         if [[ "$MRP_RUNNING" -eq 1 ]]; then
             su - {{ db_oracle_user }} -c "sqlplus -s / as sysdba" <<SQL | tee -a "$MASTER_LOG"
