Update standby_config.sh.j2

diff --git a/roles/standby_config/templates/standby_config.sh.j2 b/roles/standby_config/templates/standby_config.sh.j2
--- a/roles/standby_config/templates/standby_config.sh.j2
+++ b/roles/standby_config/templates/standby_config.sh.j2
@@ -81,8 +81,22 @@ SID_LIST_LISTENER =
 EOL
     fi
  
-    su - {{ grid_user }} -c $GRID_HOME/bin/lsnrctl reload | tee -a "$MASTER_LOG"
-    su - {{ grid_user }} -c $GRID_HOME/bin/lsnrctl status | tee -a "$MASTER_LOG"
+    su - {{ grid_user }} -c "$GRID_HOME/bin/lsnrctl reload" | tee -a "$MASTER_LOG"
+if [ ${PIPESTATUS[0]} -eq 0 ]; then
+    echo "Listener reload successful" | tee -a "$MASTER_LOG"
+else
+    echo "Listener reload failed" | tee -a "$FAILURE_LOG"
+    exit 1
+fi
+
+su - {{ grid_user }} -c "$GRID_HOME/bin/lsnrctl status" | tee -a "$MASTER_LOG"
+if [ ${PIPESTATUS[0]} -eq 0 ]; then
+    echo "Listener is running successfully" | tee -a "$MASTER_LOG"
+else
+    echo "Listener status check failed" | tee -a "$FAILURE_LOG"
+    exit 1
+fi
+
 
     # Create an initialization parameter with only DB_NAME
   echo "DB_NAME=${PRIMARY_DB_NAME}" > "$PFILE"
